server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Aktiv keshlash (hash bilan boy faylar uchun 1 yil)
    location /assets/ {
        try_files $uri =404;
        expires 1y;
        access_log off;
        add_header Cache-Control "public, immutable";
    }

    # SPA fallback — har qanday yo'lda index.html qaytariladi
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Gzip
    gzip on;
    gzip_types text/plain text/css application/json application/javascript
        application/x-javascript text/xml application/xml application/xml+rss
        text/javascript image/svg+xml;
    gzip_min_length 1024;

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
}
